### ISSUE TITLE
Missing CONTRIBUTING.md and PR/Issues templates

### ISSUE THREAD

**Issue by monesidn** [mobxjs/serializr#170]
As today no CONTRIBUTING.md file is available to provide instructions on how to contribute to the project. Also PRs and Issues doesn't have a template at all which surely doesn't help people willing to help with the project. 

Obviously I can provide such templates and roll up a CONTRIBUTING.md myself, is there anything I should pay extra attention to?

**Comment by mressler** [comment]
@monesidn - I would love to contribute. I cloned the repo and tried a number of the npm scripts in the package.json, but I couldn't get any of the tests to complete. There are some tests I would like to update and a few issues I could fix if I could get my IDE set up to contribute.

**Comment by mressler** [comment]
I'm new to TypeScript development, sorry if that was an obvious thing to try. I've been using `npm` for my build process in the library that is using `serializr`. Perhaps I have a version mismatch somewhere, because I'm getting the following:

```
mressler@dk-pirates serializr % yarn install
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 247ms
➤ YN0000: Done in 0s 556ms
mressler@dk-pirates serializr % yarn build

src/serializr.ts → lib, lib, lib, lib...
created lib, lib, lib, lib in 1.2s
mressler@dk-pirates serializr % yarn test
Error: [BABEL]: --- PLACEHOLDER PACKAGE ---
This @babel/plugin-proposal-private-property-in-object version is not meant to
be imported. Something is importing
@babel/plugin-proposal-private-property-in-object without declaring it in its
dependencies (or devDependencies) in the package.json file.
Add "@babel/plugin-proposal-private-property-in-object" to your devDependencies
to work around this error. This will make this message go away.
 (While processing: /Users/mressler/Development/serializr/node_modules/@babel/plugin-proposal-private-property-in-object/lib/index.js)
    at Object.<anonymous> (/Users/mressler/Development/serializr/node_modules/@babel/plugin-proposal-private-property-in-object/lib/index.js:28:7)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at startHiding - secret - don't use this - v1 (/Users/mressler/Development/serializr/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:55:12)
    at loadCjsDefault (/Users/mressler/Development/serializr/node_modules/@babel/core/lib/config/files/module-types.js:59:65)
    at loadCodeDefault (/Users/mressler/Development/serializr/node_modules/@babel/core/lib/config/files/module-types.js:112:18)
```

**Comment by monesidn** [comment]
Oh I accidentally stumbled upon this the other day. You probably runned `npm install` and then called `yarn`. Unfortunately this, for reasons unknown to me, mess up the dependency tree. 

The solution is actually pretty simple. Revert the changes you have in your working directory (you should see a few files) and run `yarn` again.

**Comment by mweststrate** [comment]
Correct, yarn (1) should be used. NPM totally ignores any yarn lock files so the dep tree will basically contain half random versions of each packages.

**Comment by mweststrate** [comment]
@mressler  I've send a GitHub invite. 

@monesidn  happy to give both of you publish rights to NPM, but for this I need your NPM user names, which is decoupled from GitHub

**Comment by monesidn** [comment]
@mweststrate for me it's actually the same as github: monesidn

**Comment by mweststrate** [comment]
@monesidn  done!

**Comment by mressler** [comment]
@mweststrate I was slow to get back to that invitation you sent and it expired. I'm back on the client side of this project and getting ready to dig back in if you can resend the invite.

Thanks!
